export const EXAMPLE_POLICIES = [
  { name: 'Euler Finance', url: 'https://www.euler.finance', coverage: '197000000' },
  { name: 'Curve Finance', url: 'https://curve.fi', coverage: '50000000' },
  { name: 'Ronin Bridge', url: 'https://bridge.roninchain.com', coverage: '625000000' },
  { name: 'Wormhole', url: 'https://wormhole.com', coverage: '320000000' },
  { name: 'Nomad Bridge', url: 'https://www.nomad.xyz', coverage: '190000000' },
  { name: 'Beanstalk Farms', url: 'https://bean.money', coverage: '182000000' },
  { name: 'Wintermute', url: 'https://www.wintermute.com', coverage: '160000000' },
  { name: 'Mango Markets', url: 'https://mango.markets', coverage: '116000000' },
  { name: 'Harmony Bridge', url: 'https://bridge.harmony.one', coverage: '100000000' },
  { name: 'Qubit Finance', url: 'https://qbt.fi', coverage: '80000000' },
  { name: 'Badger DAO', url: 'https://badger.com', coverage: '120000000' },
  { name: 'Poly Network', url: 'https://poly.network', coverage: '600000000' },
  { name: 'Cream Finance', url: 'https://cream.finance', coverage: '130000000' },
  { name: 'PancakeBunny', url: 'https://pancakebunny.finance', coverage: '45000000' },
  { name: 'Spartan Protocol', url: 'https://spartanprotocol.org', coverage: '30000000' },
  { name: 'Alpha Homora', url: 'https://alphafinance.io', coverage: '37000000' },
  { name: 'Meerkat Finance', url: 'https://meerkat.finance', coverage: '31000000' },
  { name: 'Uranium Finance', url: 'https://uranium.finance', coverage: '50000000' },
  { name: 'Pickle Finance', url: 'https://pickle.finance', coverage: '20000000' },
  { name: 'Harvest Finance', url: 'https://harvest.finance', coverage: '34000000' }
];

export const EXAMPLE_CLAIMS = [
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/euler-rekt/',
    explorerUrl: 'https://etherscan.io/address/0x27182842E098f60e3D576794A5bFFb0777E025d3',
    description: 'Euler Finance flash loan exploit - $197M drained via donation attack on eDAI market. Attacker used flash loan to manipulate collateral and borrow funds without proper backing.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/ronin-rekt/',
    explorerUrl: 'https://etherscan.io/address/0x098B716B8Aaf21512996dC57EB0615e2383E2f96',
    description: 'Ronin Bridge hack - $625M stolen. Attacker compromised 5 of 9 validator private keys and forged fake withdrawals from the bridge contract.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/curve-vyper-rekt/',
    explorerUrl: 'https://etherscan.io/address/0x8301AE4fc9c624d1D396cbDAa1ed877821D7C511',
    description: 'Curve Finance reentrancy exploit due to Vyper compiler bug in versions 0.2.15-0.3.0. Multiple pools drained via read-only reentrancy vulnerability.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/wormhole-rekt/',
    explorerUrl: 'https://solscan.io/tx/WormholeExploitTx',
    description: 'Wormhole bridge exploit - $320M stolen due to signature verification bypass on Solana side of the bridge.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/nomad-rekt/',
    explorerUrl: 'https://etherscan.io/address/0xNomadBridgeAddress',
    description: 'Nomad bridge drained for $190M due to a flawed initialization configuration that allowed spoofed transaction roots to be accepted.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/beanstalk-rekt/',
    explorerUrl: 'https://etherscan.io/tx/BeanstalkExploit',
    description: 'Beanstalk Farms exploited for $182M via a flash loan-assisted governance takeover. Attacker passed a malicious proposal to drain funds.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/wintermute-rekt/',
    explorerUrl: 'https://etherscan.io/address/0xWintermuteWallet',
    description: 'Wintermute lost $160M due to a compromised private key generated by the flawed Profanity tool.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/mango-markets-rekt/',
    explorerUrl: 'https://solscan.io/tx/MangoExploitTx',
    description: 'Mango Markets exploited for $116M through oracle price manipulation of the MNGO token, allowing the attacker to take out massive undercollateralized loans.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/harmony-horizon-rekt/',
    explorerUrl: 'https://etherscan.io/address/0xHarmonyBridge',
    description: 'Harmony Horizon bridge hacked for $100M after attacker compromised 2 of 5 multisig keys.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/qubit-rekt/',
    explorerUrl: 'https://bscscan.com/address/0xQubitFinance',
    description: 'Qubit Finance exploited for $80M via an uninitialized bridge contract flaw that allowed minting unbounded xETH.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/badger-rekt/',
    explorerUrl: 'https://etherscan.io/address/0xBadgerDAO',
    description: 'Badger DAO front-end attack led to $120M loss. Attackers injected malicious scripts via Cloudflare API to hijack user approvals.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/poly-network-rekt/',
    explorerUrl: 'https://etherscan.io/address/0xPolyNetwork',
    description: 'Poly Network exploited for $600M due to a vulnerability in the contract execution function allowing arbitrary cross-chain calls.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/cream-finance-rekt/',
    explorerUrl: 'https://etherscan.io/address/0xCreamFinance',
    description: 'Cream Finance flash loan exploit resulting in $130M loss. Attacker manipulated the yUSD oracle price.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/pancakebunny-rekt/',
    explorerUrl: 'https://bscscan.com/address/0xPancakeBunny',
    description: 'PancakeBunny flash loan attack led to $45M loss. Attacker manipulated the BUNNY/BNB price oracle to mint massive amounts of BUNNY.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/spartan-protocol-rekt/',
    explorerUrl: 'https://bscscan.com/address/0xSpartanProtocol',
    description: 'Spartan Protocol exploited for $30M via a flawed liquidity calculation logic during swap operations.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/alpha-homora-rekt/',
    explorerUrl: 'https://etherscan.io/address/0xAlphaHomora',
    description: 'Alpha Homora V2 exploited for $37M using a complex flash loan chain to abuse the sUSD pool rounding mechanism.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/meerkat-finance-rekt/',
    explorerUrl: 'https://bscscan.com/address/0xMeerkatFinance',
    description: 'Meerkat Finance rug pull/exploit led to $31M drained via compromised deployer keys shortly after launch.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/uranium-finance-rekt/',
    explorerUrl: 'https://bscscan.com/address/0xUraniumFinance',
    description: 'Uranium Finance exploited for $50M due to a bug in their custom pair matching logic, allowing the attacker to drain liquidity.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/pickle-finance-rekt/',
    explorerUrl: 'https://etherscan.io/address/0xPickleFinance',
    description: 'Pickle Finance exploited for $20M through a complex flash loan attack targeting the pDAI jar.'
  },
  {
    policyId: '0',
    evidenceUrl: 'https://rekt.news/harvest-finance-rekt/',
    explorerUrl: 'https://etherscan.io/address/0xHarvestFinance',
    description: 'Harvest Finance exploited for $34M via an arbitrage attack manipulating USDC/USDT prices in the Curve Y pool.'
  }
];
